package com.example.codegenapplication

import com.example.processor.AutoGeneratedCalculator
import com.example.processor.SUM

@AutoGeneratedCalculator("This is a calculator class")
interface Calculator {

    @SUM("Sum the values")
    fun sum(a: Int, b: Int): Int
}